CREATE TABLE {table} (
        vendor_id smallint,
        lpep_pickup_datetime timestamp,
        lpep_dropoff_datetime timestamp,
        store_and_fwd_flag char,
        ratecode_id smallint,
        pulocation_id smallint,
        dolocation_id smallint,
        passenger_count smallint,
        trip_distance real,
        fare_amount real,
        extra real,
        mta_tax real,
        tip_amount real,
        tolls_amount real,
        ehail_fee char,
        improvement_surcharge real,
        total_amount real,
        payment_type smallint,
        trip_type smallint,
        congestion_surcharge real
)